package com.miniweibo.user.module.user.entity;

import java.util.Date;

public class UserExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.id
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.uid
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.latest_topic_id
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Long latestTopicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.follow_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Integer followCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.fans_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Integer fansCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.comment_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.reply_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Integer replyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.topic_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Integer topicCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.create_time
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.update_time
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_ext.is_deleted
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.id
     *
     * @return the value of user_ext.id
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.id
     *
     * @param id the value for user_ext.id
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.uid
     *
     * @return the value of user_ext.uid
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.uid
     *
     * @param uid the value for user_ext.uid
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.latest_topic_id
     *
     * @return the value of user_ext.latest_topic_id
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Long getLatestTopicId() {
        return latestTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.latest_topic_id
     *
     * @param latestTopicId the value for user_ext.latest_topic_id
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setLatestTopicId(Long latestTopicId) {
        this.latestTopicId = latestTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.follow_count
     *
     * @return the value of user_ext.follow_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Integer getFollowCount() {
        return followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.follow_count
     *
     * @param followCount the value for user_ext.follow_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setFollowCount(Integer followCount) {
        this.followCount = followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.fans_count
     *
     * @return the value of user_ext.fans_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Integer getFansCount() {
        return fansCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.fans_count
     *
     * @param fansCount the value for user_ext.fans_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setFansCount(Integer fansCount) {
        this.fansCount = fansCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.comment_count
     *
     * @return the value of user_ext.comment_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.comment_count
     *
     * @param commentCount the value for user_ext.comment_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.reply_count
     *
     * @return the value of user_ext.reply_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Integer getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.reply_count
     *
     * @param replyCount the value for user_ext.reply_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.topic_count
     *
     * @return the value of user_ext.topic_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Integer getTopicCount() {
        return topicCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.topic_count
     *
     * @param topicCount the value for user_ext.topic_count
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setTopicCount(Integer topicCount) {
        this.topicCount = topicCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.create_time
     *
     * @return the value of user_ext.create_time
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.create_time
     *
     * @param createTime the value for user_ext.create_time
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.update_time
     *
     * @return the value of user_ext.update_time
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.update_time
     *
     * @param updateTime the value for user_ext.update_time
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_ext.is_deleted
     *
     * @return the value of user_ext.is_deleted
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_ext.is_deleted
     *
     * @param isDeleted the value for user_ext.is_deleted
     *
     * @mbg.generated Sat Sep 05 23:17:16 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}