package com.miniweibo.comment.modules.reply.entity;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.topic_id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.comment_id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.uid
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.create_time
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.update_time
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.is_deleted
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.topic_id
     *
     * @return the value of reply.topic_id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.topic_id
     *
     * @param topicId the value for reply.topic_id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.comment_id
     *
     * @return the value of reply.comment_id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.comment_id
     *
     * @param commentId the value for reply.comment_id
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.uid
     *
     * @return the value of reply.uid
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.uid
     *
     * @param uid the value for reply.uid
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.create_time
     *
     * @return the value of reply.create_time
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.create_time
     *
     * @param createTime the value for reply.create_time
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.update_time
     *
     * @return the value of reply.update_time
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.update_time
     *
     * @param updateTime the value for reply.update_time
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.is_deleted
     *
     * @return the value of reply.is_deleted
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.is_deleted
     *
     * @param isDeleted the value for reply.is_deleted
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbg.generated Sat Sep 05 22:48:06 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }
}