package com.miniweibo.feed.modules.feed.entity;

import java.util.Date;

public class Feed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.topic_id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.user_id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.create_time
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.update_time
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.is_deleted
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.id
     *
     * @return the value of feed.id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.id
     *
     * @param id the value for feed.id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.topic_id
     *
     * @return the value of feed.topic_id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.topic_id
     *
     * @param topicId the value for feed.topic_id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.user_id
     *
     * @return the value of feed.user_id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.user_id
     *
     * @param userId the value for feed.user_id
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.create_time
     *
     * @return the value of feed.create_time
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.create_time
     *
     * @param createTime the value for feed.create_time
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.update_time
     *
     * @return the value of feed.update_time
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.update_time
     *
     * @param updateTime the value for feed.update_time
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.is_deleted
     *
     * @return the value of feed.is_deleted
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.is_deleted
     *
     * @param isDeleted the value for feed.is_deleted
     *
     * @mbg.generated Sat Sep 05 22:50:13 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}