server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miniweibo?useUnicode&characterEncoding=UTF-8&useSSL=false&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.miniweibo.**.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
jwt:
  secret: com.miniweibo.user